### ISSUE TITLE
EMK file support

### ISSUE THREAD

**Issue by korewaChino** [RustyKaraoke/RustyKaraoke#1]
EMK is (supposedly) a container file format for NCN karaoke files used by eXtreme Karaoke.

It is supposedly a compressed archive containing a MIDI, a plaintext in TIS-620, and an array of u16s for timing.

It is currently unknown how to process, read and extract this file format.

There is a tool called EMKMan that comes with eXtreme Karaoke that can archive a folder of NCN files (lyr, mid, cur) into a folder of EMKs. It is written in Delphi Pascal and I have failed to decompile it. Documentation all points to this proprietary tool and nothing else, and most of them is in Thai.

I will provide any resources and examples on the format.

## Notes about eXtreme Karaoke

eXtreme Karaoke is a proprietary karaoke player for Windows. Its primary format of songs are in EMKs and XMKs, the latter of which is encrypted with DRM.

According to Ghidra, the software itself is written in Delphi Pascal and makes use of libbass and WinMCI.

eXtreme Karaoke also has a dongle DRM, which was the reason why RustyKaraoke was created, as HandyKaraoke's development is dead.

Website: http://www.karaoke-soft.com/

**Comment by alula** [comment]
Yep, it indeed seems to be a container for NCN files.

Every file is just scrambled with static XOR key (`AFF24C9CE9EA9943`).
There's a short header which has some irrelevant data which points to second set of headers which then uses some kind of simple tagged format.
The actual data is just a set of concatenated zlib compressed blobs.

Here's some code that parses and extracts it: https://gist.github.com/alula/2c1edc360772b3bcde4de85ca731ae71

**Comment by alula** [comment]
also the 16 byte thing I skipped over is a MD5 hash of the uncompressed data

**Comment by korewaChino** [comment]
Thanks for the example code!

I will try to reimplement this in Rust.

**Comment by korewaChino** [comment]
Implemented decoder in Rust. Will add it to loader soon.

**Comment by korewaChino** [comment]
Completed with refactor. Credits to @pastelite
